
import { firebaseConfig, firebaseReady } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, addDoc, query, onSnapshot, serverTimestamp, getDocs, orderBy, limit } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const screen=document.getElementById("screen"),toastBox=document.getElementById("toast"),authTopBtn=document.getElementById("authTopBtn");
let app,auth,db,currentUser=null,profile=null,currentChatId="demo-chat",board=Array(9).fill(""),turn="X",gameOver=false;
let localMessages=[{from:"other",text:"Ciao, sono vicino a te."},{from:"me",text:"Messaggio demo."}];
const interests=["Musica","Viaggi","Sport","Fotografia","Natura","Caffè","Aperitivo","Cinema","Metal detecting","Palestra"];
const stickers=[["assets/sticker-caffe.jpg","Caffè insieme?"],["assets/sticker-fuoco.jpg","Sei una bomba"],["assets/sticker-banana.jpg","L’unico frutto dell’amor"],["assets/sticker-pesca.jpg","Che chiappe"],["assets/sticker-drink.jpg","Drink"],["assets/sticker-limone.jpg","Bacio"],["assets/sticker-scopa.jpg","Motel"],["assets/sticker-pere.jpg","Che meloni"]];

if(firebaseReady){app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);onAuthStateChanged(auth,async u=>{currentUser=u;authTopBtn.textContent=u?"Esci":"Accedi";if(u){await loadProfile();show("vicini")}else{profile=null;home()}})}else home();

document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>show(b.dataset.view)));
authTopBtn.onclick=async()=>{if(currentUser&&firebaseReady)await signOut(auth);else if(currentUser){currentUser=null;profile=null;authTopBtn.textContent="Accedi";home()}else showLogin()};

function setActive(v){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));let a=document.querySelector(`[data-view="${v}"]`);if(a)a.classList.add("active")}
function show(v){setActive(v);if(!currentUser&&v!=="home"){showLogin();return}({home, vicini:nearbyView, sticker:stickerView, chat:chatView, profilo:profileView, tris:trisView, menu:menuView}[v]||home)()}
function home(){setActive("");screen.innerHTML=`<section class="panel"><h2 class="screen-title">Benvenuto</h2><p class="info">Accedi, registrati oppure entra in demo locale.</p><button class="wood-btn" onclick="showLogin()">Accedi / Registrati</button><button class="green" onclick="demoAccess()">Demo locale</button><p class="info">Firebase: ${firebaseReady?"configurato":"non configurato"}</p></section>`}
window.showLogin=function(){screen.innerHTML=`<section class="panel"><h2 class="screen-title">Accesso</h2><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><div class="two"><button class="wood-btn" onclick="login()">Accedi</button><button class="green" onclick="register()">Registrati</button></div><button class="primary" onclick="demoAccess()">Demo locale</button></section>`}
window.login=async function(){let email=value("email"),password=value("password");if(!email||!password)return toast("Inserisci email e password");try{if(!firebaseReady)return demoAccess();await signInWithEmailAndPassword(auth,email,password)}catch(e){toast("Errore login: "+readableError(e))}}
window.register=async function(){let email=value("email"),password=value("password");if(!email||password.length<6)return toast("Password minimo 6 caratteri");try{if(!firebaseReady)return demoAccess();let cred=await createUserWithEmailAndPassword(auth,email,password);await setDoc(doc(db,"users",cred.user.uid),defaultProfile(cred.user));toast("Registrazione completata")}catch(e){toast("Errore registrazione: "+readableError(e))}}
window.demoAccess=function(){currentUser={uid:"demo-user",email:"demo@meetreact.local"};profile={uid:"demo-user",email:"demo@meetreact.local",name:"Marco",age:"23",bio:"Amo viaggiare, musica indie e tramonti al mare.",interests:["Musica","Viaggi","Sport","Fotografia","Natura"],photo:"",lat:null,lng:null,updatedAt:Date.now()};authTopBtn.textContent="Esci";show("vicini");toast("Demo locale attiva")}
function defaultProfile(u){return{uid:u.uid,email:u.email,name:"Nuovo profilo",age:"",bio:"",interests:[],photo:"",lat:null,lng:null,updatedAt:Date.now()}}
async function loadProfile(){if(!firebaseReady||!currentUser)return;let ref=doc(db,"users",currentUser.uid),snap=await getDoc(ref);profile=snap.exists()?snap.data():defaultProfile(currentUser);if(!snap.exists())await setDoc(ref,profile)}
async function saveProfileToDb(){if(firebaseReady&&currentUser?.uid!=="demo-user")await setDoc(doc(db,"users",currentUser.uid),profile,{merge:true})}

function nearbyView(){screen.innerHTML=`<h2 class="screen-title">Persone vicine</h2><section class="panel"><button class="green" onclick="updateGPS()">Aggiorna posizione GPS</button><p class="info">Mostra profili entro 300 metri. Su Netlify/Vercel il GPS funziona perché c’è HTTPS.</p><div id="nearbyList"></div></section>`;renderNearbyDemo();if(firebaseReady&&currentUser?.uid!=="demo-user")listenNearby()}
window.updateGPS=function(){if(!navigator.geolocation)return toast("GPS non supportato");navigator.geolocation.getCurrentPosition(async pos=>{profile.lat=pos.coords.latitude;profile.lng=pos.coords.longitude;profile.updatedAt=Date.now();await saveProfileToDb();toast("GPS aggiornato");nearbyView()},()=>toast("Permesso GPS negato"),{enableHighAccuracy:true,timeout:12000,maximumAge:20000})}
function renderNearbyDemo(){let list=document.getElementById("nearbyList");if(!list)return;list.innerHTML=`<article class="panel user-card"><div class="avatar">🙂</div><div><h3>Profilo test, 29</h3><span class="badge">● 120 m</span><p class="info">Utente dimostrativo entro 300 metri.</p><div class="chips"><span class="chip">Caffè</span><span class="chip">Viaggi</span><span class="chip">Aperitivo</span></div><button class="wood-btn" onclick="openChat('demo-chat')">Apri chat</button><button class="primary" onclick="challengeTris()">Sfida a tris</button></div></article>`}
async function listenNearby(){if(!profile?.lat||!profile?.lng)return;let list=document.getElementById("nearbyList"),snap=await getDocs(query(collection(db,"users"),limit(50))),rows=[];snap.forEach(s=>{let u=s.data();if(u.uid===currentUser.uid||!u.lat||!u.lng)return;let d=distanceMeters(profile.lat,profile.lng,u.lat,u.lng);if(d<=300)rows.push({...u,distance:Math.round(d)})});if(rows.length)list.innerHTML=rows.map(u=>`<article class="panel user-card"><div class="avatar">${u.photo?`<img src="${escapeHtml(u.photo)}">`:"🙂"}</div><div><h3>${escapeHtml(u.name||"Profilo")}, ${escapeHtml(u.age||"")}</h3><span class="badge">● ${u.distance} m</span><p class="info">${escapeHtml(u.bio||"")}</p><button class="wood-btn" onclick="openChat('${u.uid}')">Apri chat</button><button class="primary" onclick="challengeTris()">Sfida a tris</button></div></article>`).join("")}
window.openChat=function(id){currentChatId=id||"demo-chat";show("chat")}

function chatView(){screen.innerHTML=`<h2 class="screen-title">Chat</h2><section class="panel"><h3>Profilo test</h3><div id="chatMessages" class="chat-box"></div><input id="messageText" placeholder="Scrivi un messaggio..."><button class="wood-btn" onclick="sendMessage()">Invia</button></section>`;if(firebaseReady&&currentUser?.uid!=="demo-user")listenChat();else renderLocalMessages()}
function renderLocalMessages(){let box=document.getElementById("chatMessages");if(box)box.innerHTML=localMessages.map(m=>`<div class="bubble ${m.from==="me"?"me":""}">${escapeHtml(m.text)}</div>`).join("")}
function listenChat(){let box=document.getElementById("chatMessages"),key=chatId(currentUser.uid,currentChatId),q=query(collection(db,"chats",key,"messages"),orderBy("createdAt","asc"),limit(80));onSnapshot(q,snap=>{box.innerHTML="";snap.forEach(ds=>{let m=ds.data();box.innerHTML+=`<div class="bubble ${m.sender===currentUser.uid?"me":""}">${escapeHtml(m.text)}</div>`})})}
window.sendMessage=async function(){let text=value("messageText");if(!text)return toast("Scrivi un messaggio");if(firebaseReady&&currentUser?.uid!=="demo-user"){await addDoc(collection(db,"chats",chatId(currentUser.uid,currentChatId),"messages"),{text,sender:currentUser.uid,createdAt:serverTimestamp()})}else{localMessages.push({from:"me",text});renderLocalMessages()}document.getElementById("messageText").value=""}

function stickerView(){screen.innerHTML=`<h2 class="screen-title">Sticker</h2><section class="grid">${stickers.map(([img,label])=>`<button class="panel sticker-card" onclick="sendSticker('${escapeAttr(label)}')"><img src="${img}" alt="${escapeAttr(label)}"><span>${escapeHtml(label)}</span></button>`).join("")}</section>`}
window.sendSticker=function(label){localMessages.push({from:"me",text:label});toast("Sticker inviato")}
function profileView(){let selected=new Set(profile?.interests||[]);screen.innerHTML=`<h2 class="screen-title">Il tuo profilo</h2><section class="panel"><div class="avatar big" id="avatarPreview">${profile?.photo?`<img src="${escapeHtml(profile.photo)}">`:"🙂"}</div><label class="wood-btn" style="display:block;text-align:center">Carica foto<input type="file" accept="image/*" onchange="loadPhoto(event)" class="hidden"></label><div class="profile-name">${escapeHtml(profile?.name||"Profilo")}, ${escapeHtml(profile?.age||"")}</div><label>Bio</label><textarea id="bio">${escapeHtml(profile?.bio||"")}</textarea><input id="name" placeholder="Nome" value="${escapeHtml(profile?.name||"")}"><input id="age" placeholder="Età" value="${escapeHtml(profile?.age||"")}"><h3>Interessi</h3><div class="interest-list">${interests.map(i=>`<label class="interest-row"><span>${iconForInterest(i)} ${escapeHtml(i)}</span><input type="checkbox" value="${escapeAttr(i)}" ${selected.has(i)?"checked":""}></label>`).join("")}</div><button class="wood-btn" onclick="saveProfile()">Salva profilo</button></section>`}
window.loadPhoto=function(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=x=>{profile.photo=x.target.result;document.getElementById("avatarPreview").innerHTML=`<img src="${profile.photo}">`};r.readAsDataURL(file)}
window.saveProfile=async function(){profile.name=value("name");profile.age=value("age");profile.bio=value("bio");profile.interests=Array.from(document.querySelectorAll(".interest-row input:checked")).map(i=>i.value);await saveProfileToDb();toast("Profilo salvato");profileView()}
window.challengeTris=function(){board=Array(9).fill("");turn="X";gameOver=false;show("tris")}
function trisView(){screen.innerHTML=`<h2 class="screen-title">Match / Tris</h2><section class="panel"><p class="info">Sfida giocosa: se vinci, sblocchi una nuova possibilità di contatto.</p><div class="tris-board">${board.map((c,i)=>`<button class="cell" onclick="playCell(${i})">${c}</button>`).join("")}</div><button class="green" onclick="resetTris()">Nuova sfida</button></section>`}
window.playCell=function(i){if(gameOver||board[i])return;board[i]=turn;if(winner(turn)){gameOver=true;toast(turn==="X"?"Hai vinto: chat bonus!":"Hai perso la sfida")}else if(board.every(Boolean)){gameOver=true;toast("Pareggio")}else turn=turn==="X"?"O":"X";trisView()}
window.resetTris=function(){board=Array(9).fill("");turn="X";gameOver=false;trisView()}
function winner(m){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(c=>c.every(i=>board[i]===m))}
function menuView(){screen.innerHTML=`<h2 class="screen-title">Menu</h2><section class="panel"><button class="wood-btn" onclick="show('profilo')">Profilo</button><button class="wood-btn" onclick="show('vicini')">Persone vicine</button><button class="wood-btn" onclick="show('sticker')">Sticker</button><button class="wood-btn" onclick="show('tris')">Match / Tris</button><button class="green" onclick="toast('Privacy: GPS usato solo per distanza entro 300 metri')">Privacy</button><button class="red" onclick="logout()">Esci</button></section>`}
window.logout=async function(){if(firebaseReady&&auth?.currentUser)await signOut(auth);currentUser=null;profile=null;authTopBtn.textContent="Accedi";home()}
function value(id){return(document.getElementById(id)?.value||"").trim()}function toast(m){toastBox.textContent=m;toastBox.style.display="block";setTimeout(()=>toastBox.style.display="none",3000)}
function readableError(e){return String(e?.code||e?.message||e).replace("auth/","")}function distanceMeters(a,b,c,d){let R=6371000,rad=x=>x*Math.PI/180,dl=rad(c-a),dn=rad(d-b),q=Math.sin(dl/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function chatId(a,b){return[a,b].sort().join("_")}function iconForInterest(i){return({Musica:"🎵",Viaggi:"✈️",Sport:"⚜️",Fotografia:"📷",Natura:"🌿",Caffè:"☕",Aperitivo:"🍹",Cinema:"🎬","Metal detecting":"🔎",Palestra:"🏋️"}[i]||"•")}function escapeHtml(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function escapeAttr(s){return escapeHtml(s).replace(/"/g,"&quot;")}
