import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, sendEmailVerification } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, getDocs, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAIydfYnvkcKVai2m6Zl7LjnsXiQnT0PMk",authDomain:"meet-react-dd136.firebaseapp.com",projectId:"meet-react-dd136",storageBucket:"meet-react-dd136.firebasestorage.app",messagingSenderId:"902511777751",appId:"1:902511777751:web:514ffef33e30d704575d92",measurementId:"G-X3SEF0W2N5"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let currentUser=null,currentProfile=null,view="nearby",nearbyUsers=[],gpsReady=false;
const interestsList=["musica","montagna","caffè","aperitivo","moda","sport","viaggi","cinema","arte","moto","palestra","cucina","natura","ballo","lettura","metal detecting"];
const stickers=[["☕","Caffè insieme?"],["🍹","Drink?"],["🔥","Sei tanta roba"],["👋","Sono qui vicino"],["💬","Parliamo due minuti?"],["🚶","Due passi?"]];
const content=document.getElementById("content"),authBtn=document.getElementById("authBtn");
document.querySelectorAll(".bottom-nav button").forEach(btn=>btn.addEventListener("click",()=>showView(btn.dataset.view)));
window.showView=v=>{view=v;render();};
authBtn.onclick=async()=>{if(currentUser){await signOut(auth);toast("Logout effettuato")}else showLogin();};
onAuthStateChanged(auth,async user=>{currentUser=user;authBtn.textContent=user?"Esci":"Login";if(user){try{await loadOrCreateProfile();await updateMyLocation(false);await loadNearbyUsers();}catch(e){toast("Errore: "+cleanError(e.message));}}else{currentProfile=null;nearbyUsers=[];gpsReady=false;}render();});
function defaultProfile(){return{uid:currentUser.uid,email:currentUser.email,name:"",age:"",bio:"",photo:"",interests:[],visible:true,profileComplete:false,lat:null,lng:null,updatedAt:Date.now()};}
async function loadOrCreateProfile(){const ref=doc(db,"users",currentUser.uid),snap=await getDoc(ref);if(snap.exists())currentProfile={...defaultProfile(),...snap.data()};else{currentProfile=defaultProfile();await setDoc(ref,currentProfile);}}
async function saveProfileToFirebase(){if(currentUser&&currentProfile)await setDoc(doc(db,"users",currentUser.uid),currentProfile,{merge:true});}
async function updateMyLocation(showMsg=true){if(!currentUser||!currentProfile)return;if(!navigator.geolocation){gpsReady=false;if(showMsg)toast("GPS non supportato");return;}navigator.geolocation.getCurrentPosition(async pos=>{gpsReady=true;currentProfile.lat=pos.coords.latitude;currentProfile.lng=pos.coords.longitude;currentProfile.updatedAt=Date.now();await saveProfileToFirebase();await loadNearbyUsers();if(showMsg)toast("Posizione aggiornata");render();},()=>{gpsReady=false;if(showMsg)toast("Permetti il GPS per vedere chi è vicino");render();},{enableHighAccuracy:true,timeout:10000});}
async function loadNearbyUsers(){nearbyUsers=[];if(!currentUser||!currentProfile||!currentProfile.lat||!currentProfile.lng)return;const qs=await getDocs(collection(db,"users"));qs.forEach(d=>{const u=d.data();if(!u.uid||u.uid===currentUser.uid||!u.profileComplete||u.visible===false||!u.lat||!u.lng)return;const distance=getDistanceMeters(currentProfile.lat,currentProfile.lng,u.lat,u.lng);if(distance<=300)nearbyUsers.push({...u,distance:Math.round(distance)});});nearbyUsers.sort((a,b)=>a.distance-b.distance);}
function render(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.remove("active"));const nav=document.getElementById("nav-"+view);if(nav)nav.classList.add("active");if(!currentUser){content.innerHTML=welcomeView();return;}if(view==="nearby")content.innerHTML=nearbyView();if(view==="profile")content.innerHTML=profileView();if(view==="stickers")content.innerHTML=stickersView();if(view==="chat")content.innerHTML=chatView();if(view==="menu")content.innerHTML=menuView();}
function welcomeView(){return `<div class="card"><h2>Benvenuto su Meet & React</h2><p class="bio">Accedi o registrati per usare l'app.</p><button class="btn primary" onclick="showLogin()">Login / Registrati</button></div>`;}
window.showLogin=function(){content.innerHTML=`<div class="card"><h2>Login / Registrazione</h2><input class="input" id="email" placeholder="Email vera" type="email"><input class="input" id="password" placeholder="Password minimo 6 caratteri" type="password"><div class="grid2"><button class="btn primary" onclick="login()">Accedi</button><button class="btn" onclick="register()">Registrati</button></div><p class="small">Prima volta: Registrati.</p></div>`;}
window.login=async()=>{try{await signInWithEmailAndPassword(auth,val("email"),val("password"));toast("Login riuscito");view="nearby";render();}catch(e){toast("Errore login: "+cleanError(e.message));}};
window.register=async()=>{try{const cred=await createUserWithEmailAndPassword(auth,val("email"),val("password"));await sendEmailVerification(cred.user);toast("Registrazione fatta. Controlla la mail.");view="profile";render();}catch(e){toast("Errore registrazione: "+cleanError(e.message));}};
function nearbyView(){let html=`<h2 class="section-title">Persone vicine</h2><div class="notice">📍 Qui vedi se qualcuno è entro 300 metri reali.</div><button class="btn green" onclick="refreshLocation()">Aggiorna posizione GPS</button>`;if(!currentProfile){return html+`<div class="card"><h2>Profilo in caricamento</h2></div>`;}if(!currentProfile.profileComplete){return html+`<div class="card"><h2>Profilo non completo</h2><p class="bio">Questa è la sezione Vicini, ma per essere visibile devi completare foto, nome e passioni.</p><button class="btn primary" onclick="showView('profile')">Completa profilo</button></div>`;}if(!gpsReady){return html+`<div class="card"><h2>GPS non attivo</h2><p class="bio">Permetti la posizione al browser.</p></div>`;}if(!nearbyUsers.length){return html+`<div class="card"><h2>Nessun utente entro 300 m</h2><p class="bio">Per testare usa un secondo telefono con un altro account.</p></div>`;}return html+nearbyUsers.map(userCard).join("");}
function userCard(u){const common=(u.interests||[]).filter(i=>(currentProfile.interests||[]).includes(i));return `<div class="card profile-preview"><div class="avatar">${u.photo?`<img src="${u.photo}">`:"🙂"}</div><div><h2 class="name">${esc(u.name)}${u.age?", "+esc(u.age):""}</h2><p class="meta">📍 ${u.distance} m • 🟢 In zona</p><p class="bio">${esc(u.bio||"")}</p><div class="chips">${(u.interests||[]).map(i=>`<span class="chip">${esc(i)}</span>`).join("")}</div><p class="common">🔥 ${common.length} interessi in comune</p><div class="grid2"><button class="btn primary" onclick="sendSticker('${u.uid}','☕ Caffè insieme?')">☕ Caffè</button><button class="btn" onclick="sendSticker('${u.uid}','🔥 Sei tanta roba')">🔥 Sticker</button></div></div></div>`;}
function profileView(){const p=currentProfile||defaultProfile();return `<h2 class="section-title">Il mio profilo</h2><div class="card"><div class="profile-head"><div class="avatar-large" id="photoPreview">${p.photo?`<img src="${p.photo}">`:"🙂"}</div><div><h2>Foto profilo</h2><p class="bio">Carica una foto reale del viso.</p><label class="file-label">📸 Carica foto<input type="file" accept="image/*" onchange="loadPhoto(event)"></label></div></div><input class="input" id="pname" placeholder="Nome" value="${esc(p.name)}"><input class="input" id="page" placeholder="Età" inputmode="numeric" value="${esc(p.age)}"><textarea id="pbio" placeholder="Bio breve">${esc(p.bio)}</textarea><h3>Passioni / interessi</h3><div class="chips">${interestsList.map(i=>`<label class="chip-check"><input type="checkbox" value="${i}" ${(p.interests||[]).includes(i)?"checked":""}><span>${i}</span></label>`).join("")}</div><button class="btn primary" onclick="saveProfile()">Salva profilo</button></div>`;}
window.loadPhoto=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{if(!currentProfile)currentProfile=defaultProfile();currentProfile.photo=ev.target.result;document.getElementById("photoPreview").innerHTML=`<img src="${currentProfile.photo}">`;toast("Foto caricata");};reader.readAsDataURL(file);};
window.saveProfile=async()=>{if(!currentProfile)currentProfile=defaultProfile();currentProfile.name=val("pname");currentProfile.age=val("page");currentProfile.bio=val("pbio");currentProfile.interests=Array.from(document.querySelectorAll(".chip-check input:checked")).map(x=>x.value);currentProfile.profileComplete=Boolean(currentProfile.name&&currentProfile.photo&&currentProfile.interests.length>0);currentProfile.updatedAt=Date.now();await saveProfileToFirebase();if(!currentProfile.profileComplete){toast("Servono nome, foto e almeno un interesse");return;}toast("Profilo salvato");await updateMyLocation(false);await loadNearbyUsers();showView("nearby");};
function stickersView(){return `<h2 class="section-title">Sticker</h2><div class="grid3">${stickers.map(s=>`<button class="sticker"><span class="emoji">${s[0]}</span>${s[1]}</button>`).join("")}</div>`;}
function chatView(){return `<h2 class="section-title">Chat</h2><div class="card"><p class="bio">La chat reale sarà il prossimo passaggio.</p></div>`;}
function menuView(){return `<h2 class="section-title">Menu</h2><div class="grid2"><button class="btn" onclick="showView('profile')">👤 Profilo</button><button class="btn" onclick="refreshLocation()">📍 Aggiorna GPS</button><button class="btn danger" onclick="authBtn.click()">🚪 Esci</button></div>`;}
window.refreshLocation=async()=>await updateMyLocation(true);
window.sendSticker=async(toUid,text)=>{await addDoc(collection(db,"messages"),{from:currentUser.uid,to:toUid,text:"Sticker: "+text,createdAt:serverTimestamp()});toast("Sticker inviato");};
function val(id){return document.getElementById(id)?.value?.trim()||"";}
function getDistanceMeters(lat1,lon1,lat2,lon2){const R=6371000,toRad=d=>d*Math.PI/180,dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function cleanError(msg){return String(msg).replace("Firebase: ","").replace("Error ","").replace("(auth/","").replace(").","");}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",3500);}
function esc(str){return String(str||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
render();